language: r
sudo: required
cache: packages

warnings_are_errors: true
r_build_args: ''
r_check_args: '--no-build-vignettes'

r:
  - oldrel
  - release
  - devel

before_install:
  - Rscript -e 'update.packages(ask = FALSE)'

r_packages:
  - devtools
  - covr

r_github_packages:
  - r-lib/devtools
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
